### ISSUE TITLE
Add a configuration file

### ISSUE THREAD

**Issue by gbrail** [30x/transicator#19]
We're proposing a bunch of new options to the change and snapshot servers -- too many for command-line parameters. Plus, in some deployment environments we want to support environment variables. We should use something like Viper for this:

https://github.com/spf13/viper

**Comment by davent** [comment]
I am working to include the use of Viper on the YR fork. Will PR when complete.

**Comment by gbrail** [comment]
Thanks.

Since Viper pulls in a bunch of other modules, please make sure that all
those dependencies are either MIT or Apache 2.0 or BSD licensed.

**Comment by davent** [comment]
I have submitted a PR now as I am away for the next few days. I have taken a look through as many of the Licenses as I can see and they appear OK but should probably be double-checked to ensure they meet with any specific requirements you may have.

**Comment by gbrail** [comment]
Thanks for contributing -- merged it and it works well. I have some ideas how to make the command line help better, so I'll work on that.
