### ISSUE TITLE
Standby status updates don't advance replication lag for slot

### ISSUE THREAD

**Issue by kriswehner** [30x/transicator#27]
One thing we noticed in testing, when looking at replication lag, we were seeing the lag numbers in bytes for the transicator clients not dropping ever.

The query for this is:
select pg_xlog_location_diff(pg_current_xlog_location(), (select restart_lsn from pg_replication_slots where slot_name='changeserver_dev'));

This appears to be due to a couple of very small errors in the updateLSN function. Pull request incoming.

**Comment by gbrail** [comment]
Thanks! Merged the fix.
