### ISSUE TITLE
Update txid values to be 64-bit, and include the epoch

### ISSUE THREAD

**Issue by kriswehner** [30x/transicator#4]
The current logical decoder plugin (like every other logical decoder plugin I can find) uses the txn_id value it gets from pg, which is the 32 bit value and is subject to xid rollover.

We need to update the plugin to emit the 64 bit txid format that postgres exposes to users, which will require changes to the protobuf that the logical decoder emits.

**Comment by gbrail** [comment]
Do you happen  to know how to get the full 64-bit transaction IDs in SQL? Right now the snapshot server fetches these during its read transaction, and then the snapshot server matches those from what is in LevelDB. So we need to fix this in two places.

**Comment by kriswehner** [comment]
I'm monkeying around with it to see if I can get it to work. I think I do, but the convenient way is marked static.

**Comment by gbrail** [comment]
Let's make sure that the values returned by "txid_current_snapshot()" in SQL are in the same 64-bit format as what we put in the logs. I assume that PG is just putting the epoch in the high 32-bits but I don't know for sure until we test.

**Comment by kriswehner** [comment]
@gbrail the function I modified is the one pg uses for txid_current_snapshot(). It's definitely just putting the epoch in the upper 32 bits. This is something I had to become intimately familiar with when we built our internal version of the changeserver.

**Comment by gbrail** [comment]
I might want to suggest that we either put the txid and epoch in separate fields in the protobuf, or add a new field. We aren't in production yet but there are a bunch of developers depending on running changeservers, and if we change the protobuf format in an incompatible way there will be an interim period of breakage. I can look at that once you're happy with the modified C code when I merge it.

**Comment by gbrail** [comment]
Merged with master. The new TID is in a new protobuf field, because we have stuff running now and I don't want to have to shut everything down and upgrade it all at once. Now the change server will be smart enough to know what to do in case the database is sending older-format records.
