### ISSUE TITLE
Add command line switch to rename _apid_scope column

### ISSUE THREAD

**Issue by kriswehner** [30x/transicator#7]
This column name will vary per-schema of users using the product. This should be as simple as a command line argument to set the column name

**Comment by kriswehner** [comment]
Initial diff for this is here: https://github.com/seatme/transicator/compare/feature/viper...seatme:feature/configure-scope-column?expand=1

It's stacked behind our viper & rocksdb work, so I'll wait until the pull requests start merging in order to get this up as a pull.

**Comment by gbrail** [comment]
Taken care of with your patch and the new "-S" flag.
